[package]
name = "gitcat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.53", features = ["derive"]}
colored = "3.0.0"
regex = "1.12.2"
serde = "1.0.228"
tokio = { version = "1.48.0", features = ["full"] }
